/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analysis-loading`; params?: Router.UnknownInputParams; } | { pathname: `/analysis-results`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts`; params?: Router.UnknownInputParams; } | { pathname: `/first-aid`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/nearest-hospital`; params?: Router.UnknownInputParams; } | { pathname: `/report-detail`; params?: Router.UnknownInputParams; } | { pathname: `/snake-guide`; params?: Router.UnknownInputParams; } | { pathname: `/submit-analysis`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_context/ThemeContext`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/analysis-loading`; params?: Router.UnknownOutputParams; } | { pathname: `/analysis-results`; params?: Router.UnknownOutputParams; } | { pathname: `/emergency-contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/first-aid`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/nearest-hospital`; params?: Router.UnknownOutputParams; } | { pathname: `/report-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/snake-guide`; params?: Router.UnknownOutputParams; } | { pathname: `/submit-analysis`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_context/ThemeContext`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/analysis-loading${`?${string}` | `#${string}` | ''}` | `/analysis-results${`?${string}` | `#${string}` | ''}` | `/emergency-contacts${`?${string}` | `#${string}` | ''}` | `/first-aid${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/nearest-hospital${`?${string}` | `#${string}` | ''}` | `/report-detail${`?${string}` | `#${string}` | ''}` | `/snake-guide${`?${string}` | `#${string}` | ''}` | `/submit-analysis${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_context/ThemeContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analysis-loading`; params?: Router.UnknownInputParams; } | { pathname: `/analysis-results`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts`; params?: Router.UnknownInputParams; } | { pathname: `/first-aid`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/nearest-hospital`; params?: Router.UnknownInputParams; } | { pathname: `/report-detail`; params?: Router.UnknownInputParams; } | { pathname: `/snake-guide`; params?: Router.UnknownInputParams; } | { pathname: `/submit-analysis`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_context/ThemeContext`; params?: Router.UnknownInputParams; };
    }
  }
}
