// types/snake.ts

export interface Snake {
  id: number;
  name: string;
  scientific: string;
  venomous: boolean;
  region: string;
  description: string;
  identification: string;
  danger: string;
  imageUrl: string;
  keyFeatures: string[];
  commonInNA?: boolean;
}

export const SNAKES_DATABASE: Snake[] = [
  // 6 Most Common Venomous Snakes in North America
  {
    id: 1,
    name: 'Copperhead',
    scientific: 'Agkistrodon contortrix',
    venomous: true,
    region: 'Eastern & Central US',
    description: 'Most common venomous snake in North America. Copper-colored head with hourglass-shaped crossbands.',
    identification: 'Hourglass bands, copper-colored head, thick body, vertical pupils',
    danger: 'MODERATE - Painful bite, rarely fatal, medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Agkistrodon_contortrix_contortrix_CDC-a.png',
    keyFeatures: ['Hourglass bands', 'Copper head', 'Vertical pupils', 'Thick body'],
    commonInNA: true,
  },
  {
    id: 2,
    name: 'Timber Rattlesnake',
    scientific: 'Crotalus horridus',
    venomous: true,
    region: 'Eastern US',
    description: 'Common in forests. Variable coloring from yellow to black with chevron pattern.',
    identification: 'Chevron pattern, rattle, thick body, vertical pupils',
    danger: 'HIGH - Potent venom, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Crotalus_horridus_%28Timber_Rattlesnake%29.jpg/1280px-Crotalus_horridus_%28Timber_Rattlesnake%29.jpg',
    keyFeatures: ['Chevron bands', 'Rattle', 'Forest dweller', 'Variable color'],
    commonInNA: true,
  },
  {
    id: 3,
    name: 'Western Diamondback Rattlesnake',
    scientific: 'Crotalus atrox',
    venomous: true,
    region: 'Southwestern US',
    description: 'Very common in Southwest. Large rattlesnake with diamond pattern and distinctive black/white tail bands.',
    identification: 'Diamond pattern, rattle, black and white tail rings',
    danger: 'HIGH - Potentially fatal, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/%28Westliche_Diamantklapperschlange%29_Crotalus_atrox.jpg/1280px-%28Westliche_Diamantklapperschlange%29_Crotalus_atrox.jpg',
    keyFeatures: ['Diamond pattern', 'Rattle', 'Black/white tail', 'Vertical pupils'],
    commonInNA: true,
  },
  {
    id: 4,
    name: 'Cottonmouth (Water Moccasin)',
    scientific: 'Agkistrodon piscivorus',
    venomous: true,
    region: 'Southeastern US',
    description: 'Common semi-aquatic snake. Opens mouth showing white interior when threatened.',
    identification: 'White mouth interior, dark coloring, thick body, found near water',
    danger: 'HIGH - Aggressive when cornered, painful bite, medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Cottonmouth_%28Agkistrodon_piscivorus%29.jpg/1280px-Cottonmouth_%28Agkistrodon_piscivorus%29.jpg',
    keyFeatures: ['White mouth', 'Near water', 'Vertical pupils', 'Dark body'],
    commonInNA: true,
  },
  {
    id: 5,
    name: 'Prairie Rattlesnake',
    scientific: 'Crotalus viridis',
    venomous: true,
    region: 'Western & Central US',
    description: 'Common in grasslands and prairies. Greenish-brown with darker blotches.',
    identification: 'Greenish color, dark blotches, rattle, heat pits',
    danger: 'HIGH - Potent venom, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Prairie_Rattlesnake.jpg/1280px-Prairie_Rattlesnake.jpg',
    keyFeatures: ['Greenish color', 'Rattle', 'Prairie dweller', 'Dark blotches'],
    commonInNA: true,
  },
  {
    id: 6,
    name: 'Pygmy Rattlesnake',
    scientific: 'Sistrurus miliarius',
    venomous: true,
    region: 'Southeastern US',
    description: 'Small but common rattlesnake. Tiny rattle makes buzzing sound like an insect.',
    identification: 'Small size, tiny rattle, gray/brown with blotches, vertical pupils',
    danger: 'MODERATE - Painful bite, medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sistrurus_miliarius_barbouri.jpg/1280px-Sistrurus_miliarius_barbouri.jpg',
    keyFeatures: ['Small size', 'Tiny rattle', 'Gray/brown', 'Insect-like buzz'],
    commonInNA: true,
  },
  {
    id: 7,
    name: 'Garter Snake',
    scientific: 'Thamnophis sirtalis',
    venomous: false,
    region: 'Throughout North America',
    description: 'Most common snake overall in North America. Three longitudinal stripes along body. Often found in gardens, parks, and near water.',
    identification: 'Three light-colored stripes, slender body, round pupils, keeled scales',
    danger: 'LOW - Non-venomous but may bite if threatened, seek medical evaluation',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Thamnophis_sirtalis_sirtalis_Wooster.jpg/1024px-Thamnophis_sirtalis_sirtalis_Wooster.jpg',
    keyFeatures: ['Three stripes', 'Slender body', 'Round pupils', 'Small size'],
    commonInNA: true,
  },
  {
    id: 8,
    name: 'Rat Snake',
    scientific: 'Pantherophis obsoletus',
    venomous: false,
    region: 'Eastern & Central US',
    description: 'Very common, excellent climber. Often found in barns, attics, and trees. Helpful for rodent control.',
    identification: 'Varies in color (black, yellow, gray), keeled scales, round pupils, long body',
    danger: 'LOW - Non-venomous, may bite defensively, clean wound and monitor',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Western_Ratsnake_%28Pantherophis_obsoletus%29_-_Flickr_-_2ndPeter_%28cropped%29.jpg/1920px-Western_Ratsnake_%28Pantherophis_obsoletus%29_-_Flickr_-_2ndPeter_%28cropped%29.jpg',
    keyFeatures: ['Varied colors', 'Good climber', 'Round pupils', 'Long body'],
    commonInNA: true,
  },
  {
    id: 9,
    name: 'Water Snake',
    scientific: 'Nerodia sipedon',
    venomous: false,
    region: 'Eastern & Central US',
    description: 'Very common near water. Often confused with cottonmouth. Heavy-bodied with dark bands.',
    identification: 'Dark bands, thick body, round pupils, found near water, flattens when threatened',
    danger: 'LOW - Non-venomous, aggressive when cornered, painful bite',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Northern_water_snake_Florida.jpg/1280px-Northern_water_snake_Florida.jpg',
    keyFeatures: ['Near water', 'Dark bands', 'Round pupils', 'Heavy body'],
    commonInNA: true,
  },
  {
    id: 10,
    name: 'Kingsnake',
    scientific: 'Lampropeltis getula',
    venomous: false,
    region: 'Throughout US',
    description: 'Common and beneficial. Eats other snakes including venomous ones. Shiny black with white/yellow bands.',
    identification: 'Black with white or yellow bands/spots, smooth scales, round pupils',
    danger: 'LOW - Non-venomous, docile temperament, rarely bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/California_kingsnake_%28Lampropeltis_getula_californiae%29.jpg/1280px-California_kingsnake_%28Lampropeltis_getula_californiae%29.jpg',
    keyFeatures: ['Black with bands', 'Smooth scales', 'Snake eater', 'Docile'],
    commonInNA: true,
  },
  {
    id: 11,
    name: 'Gopher Snake',
    scientific: 'Pituophis catenifer',
    venomous: false,
    region: 'Western US',
    description: 'Common in western states. Often mistaken for rattlesnake due to defensive behavior (hissing, tail vibrating).',
    identification: 'Brown blotches on tan/yellow body, pointed snout, round pupils, mimics rattlesnake',
    danger: 'LOW - Non-venomous, may bluff strike and hiss loudly',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Pacific_Gopher_Snake.jpg/1280px-Pacific_Gopher_Snake.jpg',
    keyFeatures: ['Brown blotches', 'Mimics rattler', 'Round pupils', 'Hisses loudly'],
    commonInNA: true,
  },
  {
    id: 12,
    name: 'Racer',
    scientific: 'Coluber constrictor',
    venomous: false,
    region: 'Throughout US',
    description: 'Fast-moving snake, usually solid colored (black, blue, or brown). Very quick and alert.',
    identification: 'Solid color, large eyes, smooth scales, very fast',
    danger: 'LOW - Non-venomous, may bite if cornered, very fast',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Black_Racer_%28Coluber_constrictor_priapus%29.jpg/1280px-Black_Racer_%28Coluber_constrictor_priapus%29.jpg',
    keyFeatures: ['Solid color', 'Very fast', 'Large eyes', 'Alert'],
    commonInNA: true,
  },
  {
    id: 13,
    name: 'Eastern Diamondback Rattlesnake',
    scientific: 'Crotalus adamanteus',
    venomous: true,
    region: 'Southeastern US',
    description: 'Largest venomous snake in North America. Dark diamond pattern along back with cream-colored borders.',
    identification: 'Diamond pattern, rattle on tail, heavy-bodied, heat-sensing pits between eyes and nostrils',
    danger: 'HIGH - Potentially fatal bite, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Adult_Crotalus_adamanteus.jpg/1280px-Adult_Crotalus_adamanteus.jpg',
    keyFeatures: ['Diamond pattern', 'Rattle on tail', 'Vertical pupils', 'Triangular head'],
  },
  {
    id: 14,
    name: 'Coral Snake',
    scientific: 'Micrurus fulvius',
    venomous: true,
    region: 'Southern US',
    description: 'Brightly colored with red, yellow, and black bands. Remember: "Red touches yellow, kill a fellow"',
    identification: 'Red-yellow-black banding pattern, small head, round pupils',
    danger: 'HIGH - Neurotoxic venom, potentially fatal, immediate medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Coral_009.jpg/1024px-Coral_009.jpg',
    keyFeatures: ['Red-yellow-black', 'Red touches yellow', 'Small head', 'Round pupils'],
  },
  {
    id: 15,
    name: 'Milk Snake',
    scientific: 'Lampropeltis triangulum',
    venomous: false,
    region: 'Throughout North America',
    description: 'Mimics coral snake coloring but harmless. Remember: "Red touches black, venom lack"',
    identification: 'Red-black-yellow banding (red touches black), round pupils',
    danger: 'LOW - Completely harmless, beneficial pest control, still evaluate bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Red_milk_snake.JPG',
    keyFeatures: ['Red touches black', 'Round pupils', 'Smooth scales', 'Harmless'],
  },
  {
    id: 16,
    name: 'Corn Snake',
    scientific: 'Pantherophis guttatus',
    venomous: false,
    region: 'Southeastern US',
    description: 'Popular pet snake. Orange-red with dark bordered blotches. Very docile.',
    identification: 'Orange/red blotches, spear-shaped head mark, smooth scales',
    danger: 'LOW - Non-venomous, extremely docile, rarely bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Corn_snake.JPG/1280px-Corn_snake.JPG',
    keyFeatures: ['Orange blotches', 'Docile', 'Spear head mark', 'Popular pet'],
  },
  {
    id: 17,
    name: 'Ribbon Snake',
    scientific: 'Thamnophis sauritus',
    venomous: false,
    region: 'Eastern US',
    description: 'Slender relative of garter snake. Four stripes, very thin, semi-aquatic.',
    identification: 'Four light stripes, very slender, long tail, near water',
    danger: 'LOW - Non-venomous, very docile, rarely bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eastern_ribbon_snake_%28Thamnophis_sauritus%29.jpg/1280px-Eastern_ribbon_snake_%28Thamnophis_sauritus%29.jpg',
    keyFeatures: ['Four stripes', 'Very thin', 'Long tail', 'Semi-aquatic'],
  },
];