// types/snake.ts

export interface Snake {
  id: number;
  name: string;
  scientific: string;
  venomous: boolean;
  region: string;
  description: string;
  identification: string;
  danger: string;
  imageUrl: string;
  keyFeatures: string[];
  commonInNA?: boolean;
}

// Special ID for unknown snakes
export const UNKNOWN_SNAKE_ID = 0;

export const SNAKES_DATABASE: Snake[] = [
  // Unknown Species - ID 0 (used as fallback)
  {
    id: UNKNOWN_SNAKE_ID,
    name: 'Unknown Species',
    scientific: 'Species not identified',
    venomous: false,
    region: 'Unknown',
    description: 'This snake could not be positively identified by our AI system. This may be due to image quality, an uncommon species not in our database, or regional variations in appearance. Please exercise caution and treat any unidentified snake as potentially dangerous.',
    identification: 'Unable to determine identifying features. If you encountered this snake, note its color patterns, head shape, body thickness, and any distinctive markings for expert identification.',
    danger: 'UNKNOWN - Exercise Caution',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Unknown_snake.svg/1200px-Unknown_snake.svg.png',
    keyFeatures: [
      'Species not in database',
      'Treat as potentially dangerous',
      'Seek expert identification',
      'Document with photos if safe',
    ],
  },
  // 6 Most Common Venomous Snakes in North America
  {
    id: 1,
    name: 'Copperhead',
    scientific: 'Agkistrodon contortrix',
    venomous: true,
    region: 'Eastern & Central US',
    description: 'Most common venomous snake in North America. Copper-colored head with hourglass-shaped crossbands.',
    identification: 'Hourglass bands, copper-colored head, thick body, vertical pupils',
    danger: 'MODERATE - Painful bite, rarely fatal, medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Agkistrodon_contortrix_contortrix_CDC-a.png',
    keyFeatures: ['Hourglass bands', 'Copper head', 'Vertical pupils', 'Thick body'],
    commonInNA: true,
  },
  {
    id: 2,
    name: 'Timber Rattlesnake',
    scientific: 'Crotalus horridus',
    venomous: true,
    region: 'Eastern US',
    description: 'Common in forests. Variable coloring from yellow to black with chevron pattern.',
    identification: 'Chevron pattern, rattle, thick body, vertical pupils',
    danger: 'HIGH - Potent venom, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Crotalus_horridus_%28Timber_Rattlesnake%29.jpg/1280px-Crotalus_horridus_%28Timber_Rattlesnake%29.jpg',
    keyFeatures: ['Chevron bands', 'Rattle', 'Forest dweller', 'Variable color'],
    commonInNA: true,
  },
  {
    id: 3,
    name: 'Western Diamondback Rattlesnake',
    scientific: 'Crotalus atrox',
    venomous: true,
    region: 'Southwestern US',
    description: 'Very common in Southwest. Large rattlesnake with diamond pattern and distinctive black/white tail bands.',
    identification: 'Diamond pattern, rattle, black and white tail rings',
    danger: 'HIGH - Potentially fatal, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/%28Westliche_Diamantklapperschlange%29_Crotalus_atrox.jpg/1280px-%28Westliche_Diamantklapperschlange%29_Crotalus_atrox.jpg',
    keyFeatures: ['Diamond pattern', 'Rattle', 'Black/white tail', 'Vertical pupils'],
    commonInNA: true,
  },
  {
    id: 4,
    name: 'Cottonmouth (Water Moccasin)',
    scientific: 'Agkistrodon piscivorus',
    venomous: true,
    region: 'Southeastern US',
    description: 'Common semi-aquatic snake. Opens mouth showing white interior when threatened.',
    identification: 'White mouth interior, dark coloring, thick body, found near water',
    danger: 'HIGH - Aggressive when cornered, painful bite, medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Cottonmouth_%28Agkistrodon_piscivorus%29.jpg/1280px-Cottonmouth_%28Agkistrodon_piscivorus%29.jpg',
    keyFeatures: ['White mouth', 'Near water', 'Vertical pupils', 'Dark body'],
    commonInNA: true,
  },
  {
    id: 5,
    name: 'Prairie Rattlesnake',
    scientific: 'Crotalus viridis',
    venomous: true,
    region: 'Western & Central US',
    description: 'Common in grasslands and prairies. Greenish-brown with darker blotches.',
    identification: 'Greenish color, dark blotches, rattle, heat pits',
    danger: 'HIGH - Potent venom, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Prairie_Rattlesnake.jpg/1280px-Prairie_Rattlesnake.jpg',
    keyFeatures: ['Greenish color', 'Rattle', 'Prairie dweller', 'Dark blotches'],
    commonInNA: true,
  },
  {
    id: 6,
    name: 'Pygmy Rattlesnake',
    scientific: 'Sistrurus miliarius',
    venomous: true,
    region: 'Southeastern US',
    description: 'Small but common rattlesnake. Tiny rattle makes buzzing sound like an insect.',
    identification: 'Small size, tiny rattle, gray/brown with blotches, vertical pupils',
    danger: 'MODERATE - Painful bite, medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sistrurus_miliarius_barbouri.jpg/1280px-Sistrurus_miliarius_barbouri.jpg',
    keyFeatures: ['Small size', 'Tiny rattle', 'Gray/brown', 'Insect-like buzz'],
    commonInNA: true,
  },
  {
    id: 7,
    name: 'Garter Snake',
    scientific: 'Thamnophis sirtalis',
    venomous: false,
    region: 'Throughout North America',
    description: 'Most common snake overall in North America. Three longitudinal stripes along body. Often found in gardens, parks, and near water.',
    identification: 'Three light-colored stripes, slender body, round pupils, keeled scales',
    danger: 'LOW - Non-venomous but may bite if threatened, seek medical evaluation',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Thamnophis_sirtalis_sirtalis_Wooster.jpg/1024px-Thamnophis_sirtalis_sirtalis_Wooster.jpg',
    keyFeatures: ['Three stripes', 'Slender body', 'Round pupils', 'Small size'],
    commonInNA: true,
  },
  {
    id: 8,
    name: 'Rat Snake',
    scientific: 'Pantherophis obsoletus',
    venomous: false,
    region: 'Eastern & Central US',
    description: 'Very common, excellent climber. Often found in barns, attics, and trees. Helpful for rodent control.',
    identification: 'Varies in color (black, yellow, gray), keeled scales, round pupils, long body',
    danger: 'LOW - Non-venomous, may bite defensively, clean wound and monitor',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Western_Ratsnake_%28Pantherophis_obsoletus%29_-_Flickr_-_2ndPeter_%28cropped%29.jpg/1920px-Western_Ratsnake_%28Pantherophis_obsoletus%29_-_Flickr_-_2ndPeter_%28cropped%29.jpg',
    keyFeatures: ['Varied colors', 'Good climber', 'Round pupils', 'Long body'],
    commonInNA: true,
  },
  {
    id: 9,
    name: 'Water Snake',
    scientific: 'Nerodia sipedon',
    venomous: false,
    region: 'Eastern & Central US',
    description: 'Very common near water. Often confused with cottonmouth. Heavy-bodied with dark bands.',
    identification: 'Dark bands, thick body, round pupils, found near water, flattens when threatened',
    danger: 'LOW - Non-venomous, aggressive when cornered, painful bite',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Northern_water_snake_Florida.jpg/1280px-Northern_water_snake_Florida.jpg',
    keyFeatures: ['Near water', 'Dark bands', 'Round pupils', 'Heavy body'],
    commonInNA: true,
  },
  {
    id: 10,
    name: 'Kingsnake',
    scientific: 'Lampropeltis getula',
    venomous: false,
    region: 'Throughout US',
    description: 'Common and beneficial. Eats other snakes including venomous ones. Shiny black with white/yellow bands.',
    identification: 'Black with white or yellow bands/spots, smooth scales, round pupils',
    danger: 'LOW - Non-venomous, docile temperament, rarely bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/California_kingsnake_%28Lampropeltis_getula_californiae%29.jpg/1280px-California_kingsnake_%28Lampropeltis_getula_californiae%29.jpg',
    keyFeatures: ['Black with bands', 'Smooth scales', 'Snake eater', 'Docile'],
    commonInNA: true,
  },
  {
    id: 11,
    name: 'Gopher Snake',
    scientific: 'Pituophis catenifer',
    venomous: false,
    region: 'Western US',
    description: 'Common in western states. Often mistaken for rattlesnake due to defensive behavior (hissing, tail vibrating).',
    identification: 'Brown blotches on tan/yellow body, pointed snout, round pupils, mimics rattlesnake',
    danger: 'LOW - Non-venomous, may bluff strike and hiss loudly',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Pacific_Gopher_Snake.jpg/1280px-Pacific_Gopher_Snake.jpg',
    keyFeatures: ['Brown blotches', 'Mimics rattler', 'Round pupils', 'Hisses loudly'],
    commonInNA: true,
  },
  {
    id: 12,
    name: 'Racer',
    scientific: 'Coluber constrictor',
    venomous: false,
    region: 'Throughout US',
    description: 'Fast-moving snake, usually solid colored (black, blue, or brown). Very quick and alert.',
    identification: 'Solid color, large eyes, smooth scales, very fast',
    danger: 'LOW - Non-venomous, may bite if cornered, very fast',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Black_Racer_%28Coluber_constrictor_priapus%29.jpg/1280px-Black_Racer_%28Coluber_constrictor_priapus%29.jpg',
    keyFeatures: ['Solid color', 'Very fast', 'Large eyes', 'Alert'],
    commonInNA: true,
  },
  {
    id: 13,
    name: 'Eastern Diamondback Rattlesnake',
    scientific: 'Crotalus adamanteus',
    venomous: true,
    region: 'Southeastern US',
    description: 'Largest venomous snake in North America. Dark diamond pattern along back with cream-colored borders.',
    identification: 'Diamond pattern, rattle on tail, heavy-bodied, heat-sensing pits between eyes and nostrils',
    danger: 'HIGH - Potentially fatal bite, requires immediate medical attention',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Adult_Crotalus_adamanteus.jpg/1280px-Adult_Crotalus_adamanteus.jpg',
    keyFeatures: ['Diamond pattern', 'Rattle on tail', 'Vertical pupils', 'Triangular head'],
  },
  {
    id: 14,
    name: 'Coral Snake',
    scientific: 'Micrurus fulvius',
    venomous: true,
    region: 'Southern US',
    description: 'Brightly colored with red, yellow, and black bands. Remember: "Red touches yellow, kill a fellow"',
    identification: 'Red-yellow-black banding pattern, small head, round pupils',
    danger: 'HIGH - Neurotoxic venom, potentially fatal, immediate medical attention required',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Coral_009.jpg/1024px-Coral_009.jpg',
    keyFeatures: ['Red-yellow-black', 'Red touches yellow', 'Small head', 'Round pupils'],
  },
  {
    id: 15,
    name: 'Milk Snake',
    scientific: 'Lampropeltis triangulum',
    venomous: false,
    region: 'Throughout North America',
    description: 'Mimics coral snake coloring but harmless. Remember: "Red touches black, venom lack"',
    identification: 'Red-black-yellow banding (red touches black), round pupils',
    danger: 'LOW - Completely harmless, beneficial pest control, still evaluate bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Red_milk_snake.JPG',
    keyFeatures: ['Red touches black', 'Round pupils', 'Smooth scales', 'Harmless'],
  },
  {
    id: 16,
    name: 'Corn Snake',
    scientific: 'Pantherophis guttatus',
    venomous: false,
    region: 'Southeastern US',
    description: 'Popular pet snake. Orange-red with dark bordered blotches. Very docile.',
    identification: 'Orange/red blotches, spear-shaped head mark, smooth scales',
    danger: 'LOW - Non-venomous, extremely docile, rarely bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Corn_snake.JPG/1280px-Corn_snake.JPG',
    keyFeatures: ['Orange blotches', 'Docile', 'Spear head mark', 'Popular pet'],
  },
  {
    id: 17,
    name: 'Ribbon Snake',
    scientific: 'Thamnophis sauritus',
    venomous: false,
    region: 'Eastern US',
    description: 'Slender relative of garter snake. Four stripes, very thin, semi-aquatic.',
    identification: 'Four light stripes, very slender, long tail, near water',
    danger: 'LOW - Non-venomous, very docile, rarely bites',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eastern_ribbon_snake_%28Thamnophis_sauritus%29.jpg/1280px-Eastern_ribbon_snake_%28Thamnophis_sauritus%29.jpg',
    keyFeatures: ['Four stripes', 'Very thin', 'Long tail', 'Semi-aquatic'],
  },
  {
    id: 18,
    name: "Bullsnake",
    scientific: "Pituophis catenifer sayi",
    venomous: false,
    region: "Central & Western US",
    description: "Large constrictor often mistaken for rattlesnakes.",
    identification: "Yellow/tan body with brown blotches; hisses loudly; rattles tail.",
    danger: "LOW - Non-venomous but defensive.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Bullsnake.jpg",
    keyFeatures: ["Large", "Hissing", "Rattlesnake mimic"],
    commonInNA: true
  },
  {
    id: 19,
    name: "Red-bellied Snake",
    scientific: "Storeria occipitomaculata",
    venomous: false,
    region: "Eastern US & Canada",
    description: "Tiny, harmless forest snake with a red/orange belly.",
    identification: "Small brown snake with red underside.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Red-bellied_snake.jpg",
    keyFeatures: ["Red belly", "Tiny"],
    commonInNA: true
  },
  {
    id: 20,
    name: "Western Hognose Snake",
    scientific: "Heterodon nasicus",
    venomous: false,
    region: "Central US",
    description: "Known for dramatic defensive displays and playing dead.",
    identification: "Upturned nose, blotches, stout body.",
    danger: "LOW (mild rear-fang venom)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/41/Heterodon_nasicus.jpg",
    keyFeatures: ["Upturned nose", "Plays dead"],
    commonInNA: true
  },
  {
    id: 21,
    name: "Eastern Hognose Snake",
    scientific: "Heterodon platirhinos",
    venomous: false,
    region: "Eastern US",
    description: "Famous for flattening its head and playing dead.",
    identification: "Wide head, upturned nose, variable color.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Heterodon_platirhinos.jpg",
    keyFeatures: ["Plays dead", "Wide head"],
    commonInNA: true
  },
  {
    id: 22,
    name: "Glossy Snake",
    scientific: "Arizona elegans",
    venomous: false,
    region: "Southwestern US",
    description: "Smooth, shiny scales resembling a glossy finish.",
    identification: "Smooth pale body with blotches.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Arizona_elegans.jpg",
    keyFeatures: ["Glossy scales"],
    commonInNA: true
  },
  {
    id: 23,
    name: "Coachwhip Snake",
    scientific: "Masticophis flagellum",
    venomous: false,
    region: "Southern US",
    description: "Long, fast-moving snake with whip-like tail.",
    identification: "Very long, slender, gradient coloration.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/CoachwhipSnake.jpg",
    keyFeatures: ["Fast", "Long"],
    commonInNA: true
  },
  {
    id: 24,
    name: "Ring-necked Snake",
    scientific: "Diadophis punctatus",
    venomous: false,
    region: "Most of US",
    description: "Small harmless snake with bright ring around neck.",
    identification: "Black body, orange or yellow ring.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/Diadophis_punctatus.jpg",
    keyFeatures: ["Ringed neck"],
    commonInNA: true
  },
  {
    id: 25,
    name: "Smooth Green Snake",
    scientific: "Opheodrys vernalis",
    venomous: false,
    region: "Northern US & Canada",
    description: "A vibrant green insect-eating species.",
    identification: "Bright green body, smooth scales.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/Opheodrys_vernalis.jpg",
    keyFeatures: ["Green color"],
    commonInNA: true
  },
  {
    id: 26,
    name: "Rough Green Snake",
    scientific: "Opheodrys aestivus",
    venomous: false,
    region: "Southeastern US",
    description: "Long, slender, bright green climbing snake.",
    identification: "Rough scales, bright green color.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/Opheodrys_aestivus.jpg",
    keyFeatures: ["Climber", "Green"],
    commonInNA: true
  },
  {
    id: 27,
    name: "Plains Garter Snake",
    scientific: "Thamnophis radix",
    venomous: false,
    region: "Central US",
    description: "Common garden snake with orange stripe.",
    identification: "Orange or yellow mid-dorsal stripe.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Thamnophis_radix.jpg",
    keyFeatures: ["Orange stripe"],
    commonInNA: true
  },
  {
    id: 28,
    name: "Western Terrestrial Garter Snake",
    scientific: "Thamnophis elegans",
    venomous: false,
    region: "Western US",
    description: "Highly variable garter snake species.",
    identification: "Side stripes, variable patterns.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Thamnophis_elegans.jpg",
    keyFeatures: ["Striped"],
    commonInNA: true
  },
  {
    id: 29,
    name: "Ground Snake",
    scientific: "Sonora semiannulata",
    venomous: false,
    region: "Southwestern US",
    description: "Small desert-dwelling species with red/orange tones.",
    identification: "Small, brightly colored.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/43/Sonora_semiannulata.jpg",
    keyFeatures: ["Small", "Colorful"],
    commonInNA: true
  },
  {
    id: 30,
    name: "Northern Black Racer",
    scientific: "Coluber constrictor constrictor",
    venomous: false,
    region: "Eastern US",
    description: "Fast, alert, solid black snake.",
    identification: "Glossy black body, white chin.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Black_Racer.jpg",
    keyFeatures: ["Fast", "Black color"],
    commonInNA: true
  },
  {
    id: 31,
    name: "Black Kingsnake",
    scientific: "Lampropeltis nigra",
    venomous: false,
    region: "Central US",
    description: "Mostly black species with speckled pattern.",
    identification: "Black with white speckles.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/54/Lampropeltis_nigra.jpg",
    keyFeatures: ["Black scales"],
    commonInNA: true
  },
  {
    id: 32,
    name: "Scarlet Kingsnake",
    scientific: "Lampropeltis elapsoides",
    venomous: false,
    region: "Southeastern US",
    description: "Small coral snake mimic.",
    identification: 'Red-black-yellow bands ("red touches black").',
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/Scarlet_kingsnake.jpg",
    keyFeatures: ["Bands", "Coral mimic"],
    commonInNA: true
  },
  {
    id: 33,
    name: "Long-nosed Snake",
    scientific: "Rhinocheilus lecontei",
    venomous: false,
    region: "Southwestern US",
    description: "Tri-colored desert snake.",
    identification: "Red, black, and cream blotches.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Rhinocheilus_lecontei.jpg",
    keyFeatures: ["Blotches"],
    commonInNA: true
  },
  {
    id: 34,
    name: "Glossy Swamp Snake",
    scientific: "Liodytes rigida",
    venomous: false,
    region: "Southeastern US",
    description: "Secretive aquatic species.",
    identification: "Brown with two dark stripes.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/88/Liodytes_rigida.jpg",
    keyFeatures: ["Aquatic"],
    commonInNA: true
  },
  {
    id: 35,
    name: "Rough Earth Snake",
    scientific: "Haldea striatula",
    venomous: false,
    region: "Southeastern US",
    description: "Small and secretive.",
    identification: "Plain gray or brown body.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Virginia_striatula.jpg",
    keyFeatures: ["Small"],
    commonInNA: true
  },
  {
    id: 36,
    name: "Smooth Earth Snake",
    scientific: "Virginia valeriae",
    venomous: false,
    region: "Eastern US",
    description: "Small and harmless.",
    identification: "Smooth scales, brown body.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Virginia_valeriae.jpg",
    keyFeatures: ["Smooth scales"],
    commonInNA: true
  },
  {
    id: 37,
    name: "Queen Snake",
    scientific: "Regina septemvittata",
    venomous: false,
    region: "Eastern US",
    description: "Aquatic snake that eats crayfish.",
    identification: "Striped belly, round pupils.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Regina_septemvittata.jpg",
    keyFeatures: ["Aquatic", "Crayfish eater"],
    commonInNA: true
  },
  {
    id: 38,
    name: "Northern Pine Snake",
    scientific: "Pituophis melanoleucus",
    venomous: false,
    region: "Eastern US",
    description: "Large burrowing species.",
    identification: "Black and white blotched body.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Pituophis_melanoleucus.jpg",
    keyFeatures: ["Large", "Burrows"],
    commonInNA: true
  },
  {
    id: 39,
    name: "Southern Black Racer",
    scientific: "Coluber constrictor priapus",
    venomous: false,
    region: "Southeastern US",
    description: "Fast, sleek species.",
    identification: "Black body with white chin.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Coluber_constrictor_priapus.jpg",
    keyFeatures: ["Fast", "Black"],
    commonInNA: true
  },
  {
    id: 40,
    name: "Southwestern Blackhead Snake",
    scientific: "Tantilla hobartsmithi",
    venomous: false,
    region: "Southwestern US",
    description: "Small secretive snake with black head.",
    identification: "Pinkish body, black head cap.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Tantilla_hobartsmithi.jpg",
    keyFeatures: ["Black head"],
    commonInNA: true
  },
  {
    id: 41,
    name: "Eastern Worm Snake",
    scientific: "Carphophis amoenus",
    venomous: false,
    region: "Eastern US",
    description: "Very small burrowing species.",
    identification: "Pink underside, tiny head.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Carphophis_amoenus.jpg",
    keyFeatures: ["Small", "Burrowing"],
    commonInNA: true
  },
  {
    id: 42,
    name: "Western Worm Snake",
    scientific: "Carphophis vermis",
    venomous: false,
    region: "Central US",
    description: "Small pink-bellied burrower.",
    identification: "Dark top, pink belly.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Carphophis_vermis.jpg",
    keyFeatures: ["Pink belly"],
    commonInNA: true
  },
  {
    id: 43,
    name: "Eastern Indigo Snake",
    scientific: "Drymarchon couperi",
    venomous: false,
    region: "Southeastern US",
    description: "Largest non-venomous snake in the US.",
    identification: "Glossy black body.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/88/Eastern_Indigo_Snake.jpg",
    keyFeatures: ["Large", "Glossy"],
    commonInNA: true
  },
  {
    id: 44,
    name: "Rough-scaled Sand Boa",
    scientific: "Charina umbratica",
    venomous: false,
    region: "Western US",
    description: "Small stout boa species.",
    identification: "Rough scales, stout body.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Charina_umbra.jpg",
    keyFeatures: ["Boa", "Stout"],
    commonInNA: true
  },
  {
    id: 45,
    name: "Night Snake",
    scientific: "Hypsiglena torquata",
    venomous: false,
    region: "Western US",
    description: "Small, mild-venomed rear-fanged species.",
    identification: "Brown blotches, vertical pupils.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Hypsiglena_torquata.jpg",
    keyFeatures: ["Nocturnal"],
    commonInNA: true
  },
  {
    id: 46,
    name: "Speckled Kingsnake",
    scientific: "Lampropeltis holbrooki",
    venomous: false,
    region: "Central US",
    description: "Known as the 'salt and pepper snake.'",
    identification: "Black body with white speckles.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Lampropeltis_holbrooki.jpg",
    keyFeatures: ["Speckled"],
    commonInNA: true
  },
  {
    id: 47,
    name: "Arizona Coral Snake",
    scientific: "Micruroides euryxanthus",
    venomous: true,
    region: "Southwestern US",
    description: "Small desert coral snake.",
    identification: "Red-yellow-black narrow bands.",
    danger: "HIGH",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/22/Micruroides_euryxanthus.jpg",
    keyFeatures: ["Coral pattern"],
    commonInNA: true
  },
  {
    id: 48,
    name: "Western Ribbon Snake",
    scientific: "Thamnophis proximus",
    venomous: false,
    region: "Central US",
    description: "Slender striped snake.",
    identification: "Long tail, stripes.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Thamnophis_proximus.jpg",
    keyFeatures: ["Stripes"],
    commonInNA: true
  },
  {
    id: 49,
    name: "Sonoran Gopher Snake",
    scientific: "Pituophis catenifer affinis",
    venomous: false,
    region: "Southwest US",
    description: "Large desert snake.",
    identification: "Blotchy brown pattern.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Pituophis_catenifer_affinis.jpg",
    keyFeatures: ["Desert"],
    commonInNA: true
  },
  {
    id: 50,
    name: "Northern Ribbon Snake",
    scientific: "Thamnophis sauritus septentrionalis",
    venomous: false,
    region: "Northern US",
    description: "Very slender semi-aquatic species.",
    identification: "Three stripes, long tail.",
    danger: "LOW",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/50/Northern_ribbon_snake.jpg",
    keyFeatures: ["Slender", "Striped"],
    commonInNA: true
  }
];

// Helper function to get a snake by ID
export const getSnakeById = (id: number): Snake | undefined => {
  return SNAKES_DATABASE.find(s => s.id === id);
};

// Helper function to check if a snake is unknown
export const isUnknownSnake = (snakeId: number): boolean => {
  return snakeId === UNKNOWN_SNAKE_ID;
};